application: ingvaras
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /CV\.pdf
  static_files: static/CV\.pdf
  upload: static/CV\.pdf

- url: /static/(.*\.(gif|png|jpg|otf|pdf))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|otf|pdf)$

- url: /.*
  script: _go_app
