application: ingvaras
version: 4
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /scripts
  static_dir: static/scripts

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico    

- url: /CV(\.pdf)?
  static_files: static/CV.pdf
  upload: static/CV.pdf

- url: /y\.gif
  static_files: static/y.gif
  upload: static/y.gif

- url: /static/(.*\.(gif|png|jpg|otf|pdf|html))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|otf|pdf|html)$

- url: /.*
  script: _go_app
